[[redirects]]
	from = "http://blaze-in-saddle.netlify.com/*"
	to = "https://www.blaze-in-saddle.com/:splat"
	status = 301
	force = true

[[redirects]]
	from = "https://blaze-in-saddle.netlify.com/*"
	to = "https://www.blaze-in-saddle.com/:splat"
	status = 301
	force = true

[[redirects]]
	from = "http://blaze-in-saddle.netlify.app/*"
	to = "https://www.blaze-in-saddle.com/:splat"
	status = 301
	force = true

[[redirects]]
	from = "https://blaze-in-saddle.netlify.app/*"
	to = "https://www.blaze-in-saddle.com/:splat"
	status = 301
	force = true
